# Makefile.macosx -*- Makefile -*-

# Options

# Here we assume that Fink or MacPorts is installed in /sw/ and we
# should check for additional includes and libraries there.

PLATFORM_CFLAGS = -I/sw/include -I/opt/local/include
PLATFORM_LDFLAGS = -L/sw/lib -I/opt/local/lib
LIBRARIAN = ar
LIBRARIAN_FLAGS = rcs
